{
 "title": "VMs",
 "tags": [
  "hosts",
  "prometheus",
  "node-exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(node_boot_time_seconds, kubernetes_node)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{kubernetes_node=~\"$node\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',kubernetes_node=~\"$node\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{kubernetes_node=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{kubernetes_node=~\"$node\"}) /  count(count(node_cpu_seconds_total{kubernetes_node=~\"$node\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "singlestat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{kubernetes_node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{kubernetes_node=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{kubernetes_node=~\"$node\", device=~\"/dev/.*\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{kubernetes_node=~\"$node\"} - node_boot_time_seconds{kubernetes_node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{kubernetes_node=~\"$node\"})",
     "legendFormat": "load1"
    },
    {
     "expr": "count(count(node_cpu_seconds_total{kubernetes_node=~\"$node\"}) by (cpu))",
     "legendFormat": "core count"
    }
   ]
  },
  {
   "title": "CPU use",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (mode) (irate(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Cores busy",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", kubernetes_node=~\"$node\"}[5m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{kubernetes_node=~\"$node\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|azv.*|cni.*|flannel.*|cal.*|lxc.*\"}[5m])",
     "legendFormat": "{{device}} outbound"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{kubernetes_node=~\"$node\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*|azv.*|cni.*|flannel.*|cal.*|lxc.*\"}[5m])",
     "legendFormat": "{{device}} inbound"
    }
   ]
  },
  {
   "title": "Disk Iops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{kubernetes_node=~\"$node\", mode!=\"idle\"}[5m])",
     "legendFormat": "{{device}}-reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{kubernetes_node=~\"$node\", mode!=\"idle\"}[5m])",
     "legendFormat": "{{device}}-writes"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{kubernetes_node=~\"$node\", mode!=\"idle\"}[5m])",
     "legendFormat": "{{device}}-written"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{kubernetes_node=~\"$node\", mode!=\"idle\"}[5m])",
     "legendFormat": "{{device}}-read"
    }
   ]
  },
  {
   "title": "Disk IO time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{kubernetes_node=~\"$node\", mode!=\"idle\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Free Space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(min by (mountpoint) (node_filesystem_avail_bytes{kubernetes_node=~\"$node\",device=~\"/dev/.*\",}/node_filesystem_size_bytes{kubernetes_node=~\"$node\",device=~\"/dev/.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}