{
 "title": "Policy Report",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Latest Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rule Execution Success Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_policy_results_total{rule_result=\"pass\"})*100/sum(kyverno_policy_results_total{})"
    }
   ]
  },
  {
   "title": "Background Scans Success Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_policy_results_total{rule_result=\"pass\", policy_background_mode=\"true\"})*100/sum(kyverno_policy_results_total{policy_background_mode=\"true\"})"
    }
   ]
  },
  {
   "title": "Cluster Policies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_type=\"cluster\"}==1) by (policy_name))"
    }
   ]
  },
  {
   "title": "Policies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_type=\"namespaced\"}==1) by (policy_name))"
    }
   ]
  },
  {
   "title": "Validate Rules",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"validate\"}==1)"
    }
   ]
  },
  {
   "title": "Generate Rules",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"generate\"}==1)"
    }
   ]
  },
  {
   "title": "Mutate Rules",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"mutate\"}==1)"
    }
   ]
  },
  {
   "title": "Failing policies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_results_total{rule_result=\"fail\"}[45s])) by (policy_name)",
     "legendFormat": "{{policy_name}}"
    }
   ]
  },
  {
   "title": "Failing policies",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "policy_report_result" }
   ]
  },
  {
   "title": "Failing policies per namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_results_total{rule_result=\"fail\"}[45s])) by (policy_name,resource_namespace)",
     "legendFormat": "{{policy_name}}-{{resource_namespace}}"
    }
   ]
  },
  { "title": "Policy-Rule Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Admission Review Results (per-rule)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kyverno_policy_results_total{rule_execution_cause=\"admission_request\"}) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Background Scan Results (per-rule)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_results_total{rule_execution_cause=\"background_scan\"}[45s])) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Admission Review Results (per-policy)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(kyverno_policy_results_total{rule_execution_cause=\"admission_request\"}) by (policy_name, rule_result)) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Background Scan Results (per-policy)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(increase(kyverno_policy_results_total{rule_execution_cause=\"background_scan\"}[45s])) by (policy_name, rule_result)) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  { "title": "Policy-Rule Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Active Policies (by policy type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{}==1) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Active Policies (by policy validation action)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{}==1) by (policy_name, policy_validation_mode)) by (policy_validation_mode)",
     "legendFormat": "audit"
    }
   ]
  },
  {
   "title": "Active Policies running in background mode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_background_mode=\"true\"}==1) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Active Namespaced Policies (by namespaces)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_namespace!=\"-\"}==1) by (policy_name, policy_namespace)) by (policy_namespace)",
     "legendFormat": "{{policy_namespace}}"
    }
   ]
  },
  {
   "title": "Active Rules (by rule type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{}==1) by (rule_type)",
     "legendFormat": "{{rule_type}}"
    }
   ]
  },
  {
   "title": "Policy-Rule Execution Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Rule Execution Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(kyverno_policy_execution_duration_seconds_sum{}) by (rule_type)",
       "legendFormat": "{{rule_type}}"
      }
     ]
    },
    {
     "title": "Average Policy Execution Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 53 },
     "yaxes": [
      { "format": "clocks" }
     ],
     "targets": [
      {
       "expr": "avg(sum(kyverno_policy_execution_duration_seconds_sum{}) by (policy_name, policy_type)) by (policy_type)",
       "legendFormat": "{{policy_type}}"
      }
     ]
    },
    {
     "title": "Overall Average Rule Execution Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(kyverno_policy_execution_duration_seconds_sum{})"
      }
     ]
    },
    {
     "title": "Overall Average Policy Execution Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(sum(kyverno_policy_execution_duration_seconds_sum{}) by (policy_name, policy_type))"
      }
     ]
    }
   ]
  },
  {
   "title": "Admission Review Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg - Admission Review Duration (by operation)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(kyverno_admission_requests_total{}) by (resource_request_operation)",
       "legendFormat": "Resource Operation: {{resource_request_operation}}"
      }
     ]
    },
    {
     "title": "Avg - Admission Review Duration (by resource kind)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 54 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(kyverno_admission_requests_total{}) by (resource_kind)",
       "legendFormat": "Resource Kind: {{resource_kind}}"
      }
     ]
    },
    {
     "title": "Rate - Incoming Admission Requests (last 5m)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kyverno_admission_requests_total{}[5m]))"
      }
     ]
    },
    {
     "title": "Avg - Overall Admission Review Duration",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(kyverno_admission_review_duration_seconds_sum{})"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Policy Changes (by change type)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kyverno_policy_changes_total{}) by (policy_change_type)",
       "legendFormat": "Change type: {{policy_change_type}}"
      }
     ]
    },
    {
     "title": "Policy Changes (by policy type)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kyverno_policy_changes_total{}) by (policy_type)",
       "legendFormat": "{{policy_type}}"
      }
     ]
    },
    {
     "title": "Total Policy Changes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kyverno_policy_changes_total{})"
      }
     ]
    },
    {
     "title": "Rate - Policy Changes Happening (last 5m)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kyverno_admission_requests_total{}[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Admission Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Admission Requests (by operation)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kyverno_admission_requests_total{}) by (resource_request_operation)",
       "legendFormat": "Resource Operation: {{resource_request_operation}}"
      }
     ]
    },
    {
     "title": "Admission Requests (by resource kind)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kyverno_admission_requests_total{}) by (resource_kind)",
       "legendFormat": "Resource Kind: {{resource_kind}}"
      }
     ]
    },
    {
     "title": "Total Admission Requests",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kyverno_admission_requests_total{})"
      }
     ]
    }
   ]
  }
 ]
}