---
stack:
  repository: https://github.com/gimlet-io/gimlet-stack-reference.git?branch=main
config:
  certManager:
    enabled: false
  civo:
    enabled: false
    host: adam.dzsak
  externalSecrets:
    enabled: false
  grafanaCloud:
    enabled: false
  kyverno:
    enabled: false
  loki:
    enabled: false
    persistence: false
    storage:
      retentionDays: 1
  nginx:
    host: adam.dzsak
  oauth2Proxy:
    enabled: false
  prometheus:
    enabled: false
    grafanaCloud:
      enabled: false
    persistence: false
  sealedSecrets:
    enabled: false
  tempo:
    enabled: false
    sampleTraceData: false
