---
stack:
  repository: https://github.com/gimlet-io/gimlet-stack-reference.git?branch=main
config:
  certManager:
    enabled: false
  civo:
    enabled: true
    host: adam.dzsak
  externalSecrets:
    enabled: true
  grafanaCloud:
    enabled: true
  kyverno:
    enabled: true
  loki:
    enabled: true
    persistence: true
    storage:
      retentionDays: 1
  nginx:
    enabled: true
    host: adam.dzsak
  oauth2Proxy:
    enabled: true
  prometheus:
    enabled: true
    grafanaCloud:
      enabled: true
    persistence: true
  sealedSecrets:
    enabled: true
  tempo:
    enabled: true
    sampleTraceData: true
