---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: 6.24.1
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 10m
  values:
    image:
      repository: grafana/grafana
      tag: 8.4.4
    sidecar:
      datasources:
        enabled: true
      dashboards:
        enabled: true
      notifiers:
        enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
        - secretName: tls-grafana
          hosts:
            - grafana.adam.dzsak
      hosts:
        - grafana.adam.dzsak
      path: /
